all:
  vars:
    repo_root: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
    app_dir: /home/{{ ansible_user }}/app/upmon
    app_url: https://upmon.r-mulyadi.com
    upmon_config:
      defaults:
        interval_sec: 120
        timeout_sec: 10
        expected_status_code: 200
        http_method: GET
      retention_days: 90
  children:
    servers:
      hosts:
        sgtent:
          ansible_user: reed
  hosts:
    localhost:
      ansible_connection: local
